### ISSUE TITLE
javascript.GetLanguage()  return unsafe.Pointer not Language

### ISSUE THREAD

**Issue by dwdcth** [alexaandru/go-tree-sitter-bare#1]
```go
package main

import (
	"github.com/alexaandru/go-sitter-forest/javascript"
	sitter "github.com/alexaandru/go-tree-sitter-bare"
)

func main() {
	parser := sitter.NewParser()
	ok := parser.SetLanguage(javascript.GetLanguage())
	if !ok {
		panic("cannot set language")
	}
}

```
It runs with error "cannot use javascript.GetLanguage() (value of type unsafe.Pointer) as *sitter.Language value in argument to parser.SetLanguage "

**Comment by alexaandru** [comment]
Appolgies for the late reply, just saw this issue.

`javascript.GetLanguage()` returning that is intentional, but I should've documented it better. The idea was to allow people to use the "forest" library with any bindings library they choose (mine, or smacker's, etc.), that's why I exposed the raw `unsafe.Pointer` and not the `sitter.Language`, but seems like the examples are now broken. 

In the example above, you need to turn the pointer into a language, you do that with `sitter.NewLanguage()`, i.e.:

```Go
ok := parser.SetLanguage(sitter.NewLanguage(javascript.GetLanguage()))
```

More verbose, but also more flexible.

**Comment by alexaandru** [comment]
Fixed the broken examples in here, and will also update the README in https://github.com/alexaandru/go-sitter-forest

Thank you for your bug report, much appreciated!
